version: '2'

services:
  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "80:8080"
    links:
      - postgres
    depends_on:
      - postgres
    volumes:
     - etc-volume:/var/gerrit/etc:rw
     - git-volume:/var/gerrit/git:rw
     - index-volume:/var/gerrit/index:rw
     - cache-volume:/var/gerrit/cache:rw
#    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit
volumes:
  etc-volume: {}
  git-volume: {}
  index-volume: {}
  cache-volume: {}

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reviewdb
    volumes:
      - db-volume:/var/lib/postgresql/data:rw
volumes:
  db-volume: {}

